services:
  - type: web
    name: corpedu-eng
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    branch: eng
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
